### ISSUE TITLE
Failed to send offers

### ISSUE THREAD

**Issue by bonomat** [itchysats/itchysats#2548] opened 2022-07-26 04:32 UTC
We see the message `Failed to send offers: Failed to negotiate protocol: Protocol negotiation failed.` quite often. 
From what I can tell the scenario is always the same: 

1. taker connects: `Connection established` is printed
2. afterwards attempts sending offers fail with `Failed to send offers`

use this loki query to see errors per peer per 5 minutes: 

```
sum by (fields_peer) (count_over_time({container="maker",setup="mainnet"} |~"Failed to send offers" | json [5m]))
```

**Comment by da-kami** [comment] 2022-08-01 12:49
I noticed that my mainnet taker keeps having trouble `receiving` the offer - it might be related: 
https://github.com/itchysats/itchysats/issues/2602

**Comment by luckysori** [comment] 2022-08-08 05:51
Duplicate of #2602.

**Closed as not planned by luckysori** 2022-08-08 05:51 UTC
