### ISSUE TITLE
Add parcel size as one of the parameters of the offer

### ISSUE THREAD

**Issue by klochowicz** [itchysats/itchysats#1266] opened 2022-01-30 23:56 UTC
We're currently relying on the implicit assumption that parcel size is `100`:
https://github.com/itchysats/itchysats/blob/master/daemon/src/projection.rs#L788

Exposing the parcel size as one of the parameters sent as a part of the offer is ultimately needed - however, in v0.4 we could probably still live with it being hard-coded to a 100, as long as we check against it.

I was quite surprised that we don't even validate against this assumption currently, as the values chosen in the actor tests don't respect it.

**Comment by luckysori** [comment] 2022-08-15 10:53
Duplicate of #2660.

**Closed as not planned by luckysori** 2022-08-15 10:53 UTC
Labels: good first issue
