### ISSUE TITLE
Flakey open_cfd_is_refunded  test: contract setup fails 

### ISSUE THREAD

**Issue by rishflab** [itchysats/itchysats#1063] opened 2022-01-10 22:23 UTC
Occurs when merging PR #1016
`af1baaacc509d9eb71af81c8690346302a3e4070`
https://github.com/itchysats/itchysats/runs/4757522364?check_suite_focus=true

I am not seeing how this failure has anything to do with the changes introduced in this PR. I think it just a flakey test.

**Comment by klochowicz** [comment] 2022-01-10 23:58
The test isn't flakey, it's caused by the single threaded scheduler in the tests and us doing a computation-heavy task inside it (contract setup). It happens on other PRs too, so I'll close this issue in favor of a more general one to track this issue:
 #1064

**Closed as completed by klochowicz** 2022-01-10 23:58 UTC
