### ISSUE TITLE
Maker randomly closes connection to taker

### ISSUE THREAD

**Issue by bonomat** [itchysats/itchysats#550] opened 2021-11-12 05:29 UTC
I don't have much information unfortunately, but the maker looks like it's randomly closing the connection to the taker: 

```
2021-11-12 16:25:16  INFO POST /api/order/sell application/json:
2021-11-12 16:25:25 DEBUG Taker wants to take an order taker_id=5a0b1a14-b7b5-4992-af26-d93aadf7032c quantity=10 order_id=b46ad6be-cdcd-4d0b-823b-7bf6f2db2ae3
2021-11-12 16:25:25  WARN Taker tried to take order with outdated id b46ad6be-cdcd-4d0b-823b-7bf6f2db2ae3
2021-11-12 16:25:36 ERROR Closing connection to taker 5a0b1a14-b7b5-4992-af26-d93aadf7032c
```

**Comment by da-kami** [comment] 2021-11-12 05:31
This happens here:

https://github.com/itchysats/itchysats/blob/b7a8370b0b4638b4359abd48577d41985cac32cf/daemon/src/maker_inc_connections.rs#L124-L135

This results in having to restart the taker (the taker does not receive new orders ..., because the connection is gone). - The taker does not see any errors. I don't understand why the maker closes  the connection at this point.

**Comment by da-kami** [comment] 2021-11-12 05:55
Did some more tests over the wire. The maker sees an incoming connections and sends an initial order:

```
2021-11-12 16:50:26 DEBUG new order Some(Order { id: OrderId(Hyphenated(b6f24ca9-35b9-4543-873d-17d00fa4c512)), trading_pair: BtcUsd, position: Short, price: Price(65047.619999999995), min_quantity: Usd(10), max_quantity: Usd(1000), leverage: Leverage(2), liquidation_price: Price(43365.079999999996666666666667), creation_timestamp: Timestamp(1636696216), settlement_time_interval_hours: Duration { seconds: 86400, nanoseconds: 0 }, origin: Ours, oracle_event_id: BitMexPriceEventId { timestamp: OffsetDateTime { utc_datetime: PrimitiveDateTime { date: Date { year: 2021, ordinal: 317 }, time: Time { hour: 6, minute: 0, second: 0, nanosecond: 0 } }, offset: UtcOffset { hours: 0, minutes: 0, seconds: 0 } }, digits: 20 } })
```

That is received on the taker side (timestamps match). 

The connection is dead, any other order created does not arrive.
There is no close connection recorded on either taker or maker.
The maker does not see an error.
The taker does not see an error. 

This does not happen every time. I started the taker multiple times and sometimes it works (and later orders are received) and sometimes it does not. It appears to be quite random.

**Comment by da-kami** [comment] 2021-11-12 06:02
After restarting the `maker` all connections opened from taker to maker (tried multiple times) worked.

My best guess is that it has something to do with not cleaning up the connections at all. Maybe we run into some kind of boundary with TCP connections (...)? 
These are wild guesses, but from the behavior seen so far I don't see anything else. 

Another wild guess:
Could closing the connection by shutting down the actor on the maker side cause weird side effects of future connections being troublesome? 

@thomaseizinger what do you think?

**Comment by thomaseizinger** [comment] 2021-11-12 06:36
Could this be the source of https://github.com/itchysats/itchysats/issues/538?

> Maybe we run into some kind of boundary with TCP connections (...)?

Very unlikely.

The closing only happens _reactively_ if the reading side of the stream shuts down. My assumption is that the taker shut down in the log you provided @bonomat. Also note the time difference of 11 seconds between the bad order and the disconnect.

**Comment by thomaseizinger** [comment] 2021-11-12 06:37
From what I can see, things work as expected here: If the reading side of the stream shuts down, the connection is useless to us so we close the writing side.

I don't think the problem description of "Maker closes connection" is accurate, we don't actively close the connection, we just react the taker disappearing.

**Comment by da-kami** [comment] 2021-11-12 06:39
But how does the taker "disappear"?

On one startup I have:

1. start the taker
2. receive an order
3. don't receive any further orders

On another startup I have:

1. start the taker
2. receive an order
3. I do receive further orders

Both startups no errors or anything that would point to closing a connection in the taker logs.


Also note that we have scenarios where the maker does not close anything but the taker does not receive further orders (after the initial one).

**Comment by thomaseizinger** [comment] 2021-11-12 07:14
We don't have a heartbeat at the moment so the connection could easily be closed be intermediate devices like routers.

**Comment by klochowicz** [comment] 2021-11-15 03:33
> We don't have a heartbeat at the moment so the connection could easily be closed be intermediate devices like routers.

heartbeat got merged in #552 , let's see whether we can reproduce the bug with it in place.

**Comment by thomaseizinger** [comment] 2021-11-15 06:59
Is this re-producible with #552 and #563 merged?

**Comment by da-kami** [comment] 2021-11-15 07:19
It was fixed with https://github.com/itchysats/itchysats/pull/559 - as stated there I was unable to reproduce it afterwards.

**Closed as completed by da-kami** 2021-11-15 07:19 UTC
Labels: bug, demo
