### ISSUE TITLE
Initial balance `0` after starting setup after longer time

### ISSUE THREAD

**Issue by da-kami** [itchysats/itchysats#1510] opened 2022-02-25 03:34 UTC
I waited for quite a while until I transferred funds. 
After transferring funds it picked up the complete balance.

I think this goes back to how many addresses we check back. But that was a temporary fix. I think we should really get the managed wallet back.

**Comment by thomaseizinger** [comment] 2022-02-25 05:15
That bug originates in BDK and needs to be fixed there.

Although I guess we can assume that users never delete their DB and as such it would be fixed by a persistent DB.

**Comment by bonomat** [comment] 2022-04-18 23:41
Duplicate of #1538

**Closed as completed by bonomat** 2022-04-18 23:41 UTC
Labels: bug
