### ISSUE TITLE
Cannot open 2nd position without restart

### ISSUE THREAD

**Issue by thomaseizinger** [itchysats/itchysats#538] opened 2021-11-11 22:29 UTC
To reproduce:

1. Start latest preview
2. Open position
3. Liquidation price drops to 0 and I cannot edit a quantity

I think this is because we don't have an offer from the maker.

Effectively, I only had 1 go at opening a position, then I had to restart the app to try again.

**Comment by da-kami** [comment] 2021-11-11 22:43
This should hopefully be fixed with https://github.com/itchysats/itchysats/pull/530 - I'll see to get that merged.
I'll keep it open until I can confirm that the problem is fixed.

**Comment by bonomat** [comment] 2021-11-14 22:03
related to #550

**Comment by da-kami** [comment] 2021-11-15 07:23
Fixed by https://github.com/itchysats/itchysats/pull/559 which fixes #550

**Closed as completed by da-kami** 2021-11-15 07:23 UTC
Labels: bug, demo
