### ISSUE TITLE
Don't retry running tests on CI

### ISSUE THREAD

**Issue by da-kami** [itchysats/itchysats#2916] opened 2022-09-09 07:30 UTC
We started re-trying tests on CI because sometimes there were conflicts with picking ports.
The problem is that, if we have flaky tests out of different reasons than ports, we might not notice because they are re-run. This can result in CI runtime going up, but the tests are "green".

In order to avoid CI failing we will have to solve the initial issue and introduce a more resilient port setup for the tests, so we can remove retries.
We could opt for using random ports locally but fixed ports for each test on CI (or similar).

**Comment by Restioson** [comment] 2022-09-09 13:12
Could we use an atomic counter for the ports, starting at some probably-free range, or just incrementing until a free port is found?

**Comment by klochowicz** [comment] 2022-09-09 18:03
Tracking the issues to be tackled in order to remove the retry:
- [ ] port conflicts - hopefully addressed by: #2923 
- [ ]  flaky rollover tests - still not done #2825

**Comment by klochowicz** [comment] 2022-09-09 18:04
@da-kami  isn't this a duplicate of your issue from last week (#2818 ) ? maybe we can close the other one?

**Comment by klochowicz** [comment] 2022-09-09 18:06
> Could we use an atomic counter for the ports, starting at some probably-free range, or just incrementing until a free port is found?

I went for the cop-out (a crate called `portpicker` that tries to generate at random and tests if they're free, and falls back to asking if it can't find any that method )

**Comment by bonomat** [comment] 2023-09-12 14:27
This project is unmaintained

**Closed as not planned by bonomat** 2023-09-12 14:27 UTC
Labels: CI
