### ISSUE TITLE
Prioritise CETs over `RefundTransaction` on restart

### ISSUE THREAD

**Issue by luckysori** [itchysats/itchysats#1230] opened 2022-01-27 05:01 UTC
Consider the following situation:

1. Parties open the CFD.
2. Either party starts force-close, publishing the `CommitTransaction`.
3. Both parties go offline.
4. Olivia publishes relevant attestation.
5. The `refund_timelock` on the `CommitTransaction` expires.
6. Either party comes back online.

Assuming that the attestation correctly unlocks one of the CETs, both the unlocked CET and the `RefundTransaction` will be accepted by the miners.  In this situation, I think our software should prioritise the CET, since the `RefundTransaction` is just a fallback mechanism when all else fails.

Recent testing has revealed that we are unintentionally prioritising the `RefundTransaction`. We're probably too eager to publish the `RefundTransaction` as soon as we notice the `refund_timelock` expiry, not giving ourselves enough time to find the attestation, unlock the CET and publish it. This theory seems to be backed by the state of the database:

```
4500d180-c56c-4bea-bab3-d35959036152|1642731266|CommitConfirmed
4500d180-c56c-4bea-bab3-35959036152|1642737793|OracleAttestedPriorCetTimelock

// restart

4500d180-c56c-4bea-bab3-35959036152|1643257379|OracleAttestedPriorCetTimelock
4500d180-c56c-4bea-bab3-d35959036152|1643257392|RefundTimelockExpired
4500d180-c56c-4bea-bab3-d35959036152|1643257392|CetTimelockExpiredPostOracleAttestation
4500d180-c56c-4bea-bab3-d35959036152|1643257718|RefundConfirmed
```

We just happen to process the expiry of the `refund_timelock` first.

**Comment by thomaseizinger** [comment] 2022-01-28 02:54
The `BitMexPriceEventId::has_likely_occured` function might come in handy here.

We could handle this within the `refund_timelock_expired` command of the `Cfd` and simply ignore it if the attestation has likely occurred. It is tricky though because if the attestation never happens, we would have missed this event.

This might require special handling within the rehydration of the monitor actor actually as it is only affects startup behaviour. During normal operation, we should broadcast refund ASAP.

**Comment by rishflab** [comment] 2022-02-17 01:00
We broadcast the CET when we start the monitor actor. We broadcast RefundTransaction via the process manager during the `sync()` method which is called periodocally.  This all happens asynchronously making it difficult to guarantee the ordering of these broadcasts.

### Options:


#### 1. If we have a valid decrypted attestation we should *never* broadcast refund
I think this is the way to go. However I am not sure what the deeper implications are of never refunding if an attestation has been received. 

IMO the correct way to implementation this solution: https://github.com/itchysats/itchysats/discussions/1434. It may be a substantial refactor.

#### 3. Send refund only after we have sent the `TryBroadcastTransaction` message containing the CET to the monitor actor
I don't think solution guarantees ordering but greatly improves the chances of the CET making it into the mempool before the . We can run into the same problem.

#### 4. Send refund only after we have successfully broadcast the CET ie. it is been accepted by node
I don't really see the point. Refund will only be accepted if the CET tx is dropped from the mempool.

#### ~Replace the refund with the cet at the mempool level~

**Comment by luckysori** [comment] 2022-02-17 01:09
> ### Options:
> #### 1. If we have the attestation we should _never_ broadcast refund.;

I think this is it, although it is important to say that we need to have a valid decrypted CET, not just an attestation.

> I think this is the way to go. However I am not sure what the deeper implications are of never refunding if an attestation has been received.

If we somehow end up not being able to broadcast the decrypted CET (for some unimaginable reason) and the application also refuses to publish the refund transaction (because of the logic we would be introducing), the money could get stuck. Luckily there is no inherent time pressure to resolve this situation and we could fix it by manually force-refunding, for example.

**Comment by rishflab** [comment] 2022-02-17 01:19
> I think this is it, although it is important to say that we need to have a valid decrypted CET, not just an attestation.

Yep good point, will update solution

**Comment by thomaseizinger** [comment] 2022-02-17 04:15
> #### 1. If we have a valid decrypted attestation we should _never_ broadcast refund
> 
> I think this is the way to go. However I am not sure what the deeper implications are of never refunding if an attestation has been received.
> 
> IMO the correct way to implementation this solution: #1434. It may be a substantial refactor.

This sounds good but does not resolve the problem during startup. In normal operation, the refund timelock expires much later than the attestation. Hence, when we witness the refund timelock event, and calling the command on the CFD produces an event (we [check](https://github.com/itchysats/itchysats/blob/96d86a2baccd0e52a16fa386335ae544619a2395/model/src/cfd.rs#L1055-L1057 that we are not closed yet), then we actually want to broadcast refund because that is exactly the case in which the oracle did not attest in time.

Concluding from that, I think we can say that the process manager behaves correctly. If the event is published, we want to broadcast refund.

The problem during startup is that two things concurrently as @rishflab correctly identified. Thus, I think any solution will have to focus on changing the way we implement the startup behaviour.

If there is a dependency between the fetching of attestations and the expiry of timelocks than this tells me that **in an ideal world**, the startup behaviour should not be isolated to the individual actors (oracle & monitor). Instead, we could have a dedicated component that, for each (open) CFD, checks certain conditions and pings the relevant actors accordingly.

Instead of blindly instructing monitor actor to check for expired timelocks, we can first estimate, if the refund timelock has already expired. (How much time has passed since the event of `CommitConfirmed`). If it has, don't monitor for it but instead, actively fetch the attestation and decrypt the CET. If it succeeds, happy days and we can move on. If it fails (because the oracle is actually gone or something like that) then we can monitor the timelock which will eventually trigger the refund part.

---

Having said all that, I think we can duct-tape this issue by simply delaying the monitoring of the refund timelock by 5 minutes on startup. That should give the oracle actor enough time to get the attestation if it already exists.

Thoughts?

**Comment by rishflab** [comment] 2022-02-17 06:07
> > #### 1. If we have a valid decrypted attestation we should _never_ broadcast refund
> > I think this is the way to go. However I am not sure what the deeper implications are of never refunding if an attestation has been received.
> > IMO the correct way to implementation this solution: #1434. It may be a substantial refactor.
> 
> This sounds good but does not resolve the problem during startup. In normal operation, the refund timelock expires much later than the attestation. Hence, when we witness the refund timelock event, and calling the command on the CFD produces an event (we [check](
> 
> https://github.com/itchysats/itchysats/blob/96d86a2baccd0e52a16fa386335ae544619a2395/model/src/cfd.rs#L1055-L1057
> that we are not closed yet), then we actually want to broadcast refund because that is exactly the case in which the oracle did not attest in time.
> 
> Concluding from that, I think we can say that the process manager behaves correctly. If the event is published, we want to broadcast refund.
> 
> The problem during startup is that two things concurrently as @rishflab correctly identified. Thus, I think any solution will have to focus on changing the way we implement the startup behaviour.
> 
> If there is a dependency between the fetching of attestations and the expiry of timelocks than this tells me that **in an ideal world**, the startup behaviour should not be isolated to the individual actors (oracle & monitor). Instead, we could have a dedicated component that, for each (open) CFD, checks certain conditions and pings the relevant actors accordingly.
> 
> Instead of blindly instructing monitor actor to check for expired timelocks, we can first estimate, if the refund timelock has already expired. (How much time has passed since the event of `CommitConfirmed`). If it has, don't monitor for it but instead, actively fetch the attestation and decrypt the CET. If it succeeds, happy days and we can move on. If it fails (because the oracle is actually gone or something like that) then we can monitor the timelock which will eventually trigger the refund part.
> 
> Having said all that, I think we can duct-tape this issue by simply delaying the monitoring of the refund timelock by 5 minutes on startup. That should give the oracle actor enough time to get the attestation if it already exists.
> 
> Thoughts?

Kinda get what you are saying.  After a restart we should actively check for an attestation and only publish refund if that fails. This issue also manifests because enough time has not been given to get the attestation after a restart. 

I will have quick look into how hard this is to implement. Otherwise will go with the duct tape solution.

**Comment by thomaseizinger** [comment] 2022-02-17 06:21
> Kinda get what you are saying. After a restart we should actively check for an attestation and only publish refund if that fails. This issue also manifests because enough time has not been given to get the attestation after a restart.
> 
> I will have quick look into how hard this is to implement. Otherwise will go with the duct tape solution.

Yeah but that interaction may be hard to implement at the moment. I _think_ any good solution for this will involve removing the start-up behaviour from monitor and oracle and combining it into one component of some kind. Is that component an actor? I don't know.

**Comment by thomaseizinger** [comment] 2022-02-22 06:49
Fixed in https://github.com/itchysats/itchysats/pull/1470.

**Closed as completed by thomaseizinger** 2022-02-22 06:49 UTC
Labels: bug
