### ISSUE TITLE
CFD has wrong state and/or wrong Tx attached

### ISSUE THREAD

**Issue by bonomat** [itchysats/itchysats#1633] opened 2022-03-15 02:59 UTC
also known as `P/L for closed CFDs might be wrong`

Sometimes, if something "unexpected" happened, we end up being in a wrong state or in the correct state but with the wrong transactions attached to the CFD. 
For example, the CFD below was closed with an outdated commit transaction on the one side and on the other side it was reported as force-closed with a different CET transaction. 
The result, the CFD is in the wrong state from which it is not be able to recover and the P/L in the CFD is wrong 

```
{
  "order_id": "a5a25751-3036-4d6a-a8c7-d83a23a024af",
  "initial_price": "43702.20",
  "accumulated_fees": -0.00006617,
  "leverage": 2,
  "trading_pair": "BtcUsd",
  "position": "Short",
  "liquidation_price": "21851.10",
  "quantity_usd": "1000",
  "margin": 0.02288215,
  "margin_counterparty": 0.01144107,
  "role": "Maker",
  "profit_btc": 0.0030732,
  "profit_percent": "13.43",
  "payout": 0.02595535,
  "closing_price": "38739",
  "state": "PendingCet",
  "actions": [],
  "details": {
    "tx_url_list": [
      {
        "label": "Cet",
        "url": "https://mempool.space/tx/1d577c13801791454cac42ae480fa0f32f2929421222b47542bda995330719e1:0"
      },
      {
        "label": "Lock",
        "url": "https://mempool.space/tx/fce6195c1821ccd55f7a92ad7a200b3466fa1c03c8c20fd8d94a10f1de51164c:0"
      },
      {
        "label": "Commit",
        "url": "https://mempool.space/tx/de7e12a51e4d03a55bf1f5f15649f36c39b7fe035441a54385ad7b54b334844a"
      }
    ]
  },
  "expiry_timestamp": 1647208800,
  "counterparty": "xxxxxx",
  "pending_settlement_proposal_price": null
},
```

**Comment by thomaseizinger** [comment] 2022-03-15 04:54
Fundamentally, I think this issue arises because we trust our own state too much and do not have a way of "overriding" that with that actually happens on the blockchain. The blockchain is obviously the source of truth.

Regarding this particular issue: This would be a case that is caught by properly monitoring for revoked transactions, correct?

**Comment by da-kami** [comment] 2022-03-16 23:25
To avoid this particular scenarios in the future we would have to work on https://github.com/itchysats/itchysats/issues/1622 potentially https://github.com/itchysats/architecture/pull/8 and https://github.com/itchysats/itchysats/issues/907.
Note: I think before we can work on punishing makers/takers we have to ensure that rollovers work more stable. In the scenario described above the taker getting punished would not be fair. It's not like the taker did anything wrong...

> The blockchain is obviously the source of truth.

We can adhere to that more, but it is not easy. The problem is monitoring. In some scenarios we just don't know that something happened because we are not monitoring for it. Take a scenario (different than the above one) where the party that finished a rollover successfully  (while the other party failed) commits. The balance would change, but besides that it would be very hard for the party that failed the rollover to update the position, because it just does not have the transactions to monitor for. We could potentially "cleanup" thing in housekeeping (see https://github.com/itchysats/itchysats/issues/1317)

I'd propose to implement all protocol paths properly and make rollover and collab settlement protocols more resilient to failing only on one side and then see how we can adhere more to what happens on the blockchain on top of that.
Ad. more resilient to error for collab settlement: https://github.com/itchysats/itchysats/issues/320

**Comment by bonomat** [comment] 2022-03-20 22:22
@da-kami: I think what you are saying makes totally sense. We have to make all protocols more resilient to failing in general. The rollover example you are bringing was very likely the source of this issue but we cannot say for sure. Maybe the taker was actually malicious and wanted to broadcast the old transaction?  
Either way, the single source of truth should be the blockchain and we should be able to overwrite our state if something happened. 

@thomaseizinger : 
> Regarding this particular issue: This would be a case that is caught by properly monitoring for revoked transactions, correct?

Yes, in the example above we would not have ended up in this state if we would have revoked the other party's commit transaction.

**Comment by da-kami** [comment] 2022-10-04 22:33
Closing this because it is not directly actionable and captured by #2465

**Closed as completed by da-kami** 2022-10-04 22:33 UTC
Labels: bug
