### ISSUE TITLE
Unable to accept/reject outdated `Offered` Cfd

### ISSUE THREAD

**Issue by da-kami** [itchysats/itchysats#1048] opened 2022-01-09 08:02 UTC
This is a scenario where I sent a take request from taker to maker, but then only wanted to pressed `Accept` after some time, because I did some things in between.

![image](https://user-images.githubusercontent.com/5557790/148674195-e4470ee1-ff39-4188-9458-0f86122049a2.png)

This is a problem, because if this happens currently the Cfd remains in `Offered` for both parties forever. We don't have any cleanup tasks, and we were not planning to create them.

In production this should rarely happen, because the maker should be available and respond timely, but we should still be more resilient against this error.

**Comment by klochowicz** [comment] 2022-01-09 22:56
@da-kami this might be duplicate of #1035  ?

**Comment by thomaseizinger** [comment] 2022-01-10 04:40
I'll close this in favor of #1035.

**Closed as completed by thomaseizinger** 2022-01-10 04:40 UTC
Labels: bug
