### ISSUE TITLE
Some of the open CFDs can be closed, some not

### ISSUE THREAD

**Issue by klochowicz** [itchysats/itchysats#1305] opened 2022-02-02 00:43 UTC
All the CFDs have the same state assigned in the UI, where clearly there is something different about them, as not all of them can be closed. This is super confusing:

![image](https://user-images.githubusercontent.com/8319440/152075054-338e7518-a3f0-4149-abef-02a2a64d3a3b.png)

**Comment by da-kami** [comment] 2022-02-02 03:58
I think #1311 should fix this, but I am surprised that you have a CFD with disabled `Close` at the end of the list... that would mean that it was not confirmed, while the others got confirmed. Did you open all at the same time?

Additionally, I am surprised that we display `Payout` with an actual link - do all of those transactions already have a payout, or was close triggered? Once we trigger the button we also lock it for the time of the request. And it seems we don't show the transaction link being unavailable correctly in dark mode. At least that's my conclusion from this screenshot.

**Comment by da-kami** [comment] 2022-02-02 04:02
This one should not be possible...

![image](https://user-images.githubusercontent.com/5557790/152091140-6055306b-ab4f-48e0-8303-e9acbbddc561.png)

I have a hard time understanding how this is happening. For `PENDING_CLOSE` we actually display `Pending Payout`.
I don't understand how it displays `Open` here. Any ideas?

**Comment by da-kami** [comment] 2022-02-02 04:15
I am unable to reproduce the display you have:

After open: 

![image](https://user-images.githubusercontent.com/5557790/152092098-79874c5e-925a-410e-8796-00003fa6ce27.png)

After clicking close:

![image](https://user-images.githubusercontent.com/5557790/152092153-92eb952d-5f28-4a48-8e38-759b07c7494a.png)

Maybe you ran into rollover while already collab closing which also maps to `Open`...?

**Comment by da-kami** [comment] 2022-02-02 04:44
After some more investigation some of these cases are likely a problem where we triggered a rollover during/at the time a collab settlement was ongoing. I will add a check for that in rollover.

**Closed as completed** 2022-02-02 05:09 UTC
