### ISSUE TITLE
Rollover protocol failed: CET signatures don't verify

### ISSUE THREAD

**Issue by da-kami** [itchysats/itchysats#1617] opened 2022-03-14 00:34 UTC
This is a production issue: mainnet maker `0.4.7`, taker version currently unknown

This is likely a problem on the taker side and are related to only one specific taker. The maker logs contains quite a lot of entries where we don't receive rollover protocol messages for CFDs related to this taker. This points to the taker running an outdated version that includes the protocol message timeouts when dispatching wire message to the rollover actors. However, we cannot know that with absolute certainty.

We see messages like this in the logs:

```
2022-03-14 09:37:14	
{"timestamp":"2022-03-13T22:37:14.734257989Z","level":"WARN","fields":{"message":"Rollover failed: Rollover protocol failed: CET signatures don't verify: enc sig on CET does not verify: failed to verify encsig spend tx: failed to verify adaptor signature","order_id":"9e6dfcf0-5108-43f9-b1de-966a26835690"},"target":"model::cfd"}
```

It appears that one party published an old commit state:

```
2022-03-14 11:00:36	
{"timestamp":"2022-03-14T00:00:36.355612096Z","level":"ERROR","fields":{"message":"Revoked logic not implemented","order_id":"a5a25751-3036-4d6a-a8c7-d83a23a024af"},"target":"model::cfd"}
```

So far 3 CFDs with this issue where identified, IDs:

```
d5981e85-0d7a-482e-acd9-b939ffc31e54
9e6dfcf0-5108-43f9-b1de-966a26835690
a5a25751-3036-4d6a-a8c7-d83a23a024af
```

All three scenarios resulted in an "old" commit state being published by the taker (because of the failed rollover on the taker side, which succeeded on the maker and all consecutive rollovers failing). The maker picked up the previous commit tx being published, but was unable to react to it, because that is currently not handled. Eventually the maker tried to publish an unrelated CET which fails.
The taker's old commit and CET went in an the position is considered closed on the taker.

## Analysis

What we know: When looking at the rollovers in the maker's database we see that the taker keeps triggering rollovers after the last successful rollover recorded by the maker. This means that the last successfully recorded rollover on the maker side failed on the taker side (because otherwise the taker would not trigger a rollover after 5 minutes again, but would wait for an hour).

The maker's rollover succeeding while the taker's failed leads to a situation where the `FeeAccount` state of the parties becomes unbalanced. The maker is one fee cycle ahead. Since the `FeeAccount` is relevant when calculating the payouts independently on each side this leads to different payouts, which leads to different CETs which leads to the verification failing on (any) next rollover.

Since we don't know what version the taker is running we can only guess why the rollover failed on the taker side. My best guess is, that the taker runs an outdated version that includes the network protocol timeouts, and the timeouts triggered at very unfortunate points in the protocol, i.e. when the taker has sent `Msg3` (the ack at the end of the rollover protocol) but did not receive it yet. 
We can see from the logs that the connection with this taker is often unstable, i.e. there are errors of losing the connection and messages not arriving in time as expected. 
It is very unlikely that this problem happens in the current version `0.4.7` because once the rollover was accepted we don't timeout the protocol. Messages to the protocol actor are dispatched synchronously. It is likely that the taker is running version `0.4.5` or `0.4.6`.

**Comment by klochowicz** [comment] 2022-03-17 04:58
Isn't this a duplicate of #1260

**Comment by thomaseizinger** [comment] 2022-04-01 01:02
Closing in favor of https://github.com/itchysats/itchysats/issues/1622.

**Closed as completed by thomaseizinger** 2022-04-01 01:02 UTC
Labels: bug
