### ISSUE TITLE
Go long button is always enabled in the taker

### ISSUE THREAD

**Issue by klochowicz** [itchysats/itchysats#542] opened 2021-11-11 23:26 UTC
New taker UI never disable disables the "buy" button

**Comment by da-kami** [comment] 2021-11-12 00:15
duplicate of #522

**Comment by bonomat** [comment] 2021-11-14 22:03
> duplicate of #522

what he said

**Closed as completed by bonomat** 2021-11-14 22:03 UTC
Labels: demo, regression

**Comment by klochowicz** [comment] 2021-11-15 00:19
> duplicate of #522

IMHO they were not duplicates, these 2 issues had a distinct feature scope - this one was simply porting from the old UI, the other one adds new functionality.

Anyway, I forgot to reference the issue in my Friday's PR: #545. It should have been closed :)
