### ISSUE TITLE
Ping protocol failed

### ISSUE THREAD

**Issue by bonomat** [itchysats/itchysats#2549] opened 2022-07-26 04:37 UTC
We see plenty of 
`outbound ping protocol failed: Timeout in protocol negotiation`
warnings on mainnet.

Use this loki query to show warnings per peer per 5 minute

```
sum by (fields_peer) (count_over_time({container="maker",setup="mainnet"} |~"ping protocol failed" | json [5m]))
```

**Comment by luckysori** [comment] 2022-08-08 05:47
Duplicate of #2602.

**Closed as not planned** 2022-08-08 05:47 UTC
