### ISSUE TITLE
Don't reuse `ContractSetup` for when rollingover

### ISSUE THREAD

**Issue by bonomat** [itchysats/itchysats#1701] opened 2022-03-28 05:06 UTC
We sometimes need to know if a CFD is open or not open. Re-using the state `ContractSetup` for when rolling over is active has weird sideeffects. 

Right now we use `ContractSetup` for the time when the contract is being setup and when it is rolledover. 

We should have a separate state here. 

https://github.com/itchysats/itchysats/blob/5ccb0a6cc6269200eb2652e57ebeaf511abe2473/daemon/src/projection.rs#L391-L393

and

https://github.com/bonomat/hermes/blob/5ccb0a6cc6269200eb2652e57ebeaf511abe2473/daemon/src/projection.rs#L268-L276

**Comment by thomaseizinger** [comment] 2022-03-28 22:40
I am tempted to close this as a duplicate of https://github.com/itchysats/itchysats/issues/1314. IMO, we should not be exposing these states and instead tell the client whether or not the CFD is open or closed with a boolean flag.

**Comment by bonomat** [comment] 2022-03-29 01:59
> I am tempted to close this as a duplicate of #1314. IMO, we should not be exposing these states and instead tell the client whether or not the CFD is open or closed with a boolean flag.

We should introduce a new state for rollover while we have states. It's just wrong to use `ContractSetup` here. 
If we go away from states, then this is not needed anymore. 
But given this is a small change, I'd be for adding the new state now.

**Closed as completed** 2022-04-07 06:21 UTC
