### ISSUE TITLE
Rollover keeps failling: missing Announcement

### ISSUE THREAD

**Issue by bonomat** [itchysats/itchysats#2762] opened 2022-08-28 11:02 UTC
latest master: 
taker side: 
```
2022-08-28 10:58:03  WARN fallible task handle_error{err=Failed to get announcement}: model::cfd: Rollover failed: Failed to get announcement: Failed to get announcements: Announcement /x/BitMEX/BXBT/2022-08-28T11:00:00.price?n=20 not found order_id=3712a56e-9e0d-4662-a9e3-3f47f3f5af6a peer_id=Some(12D3KooWEsK2X8Tp24XtyWh7DM65VfwXtNH2cmfs2JsWmkmwKbV1)
```

Announcement is available at the time of writing: https://outcome.observer/h00.ooo/x/BitMEX/BXBT/2022-08-28T11:00:00.price?n=20

**Comment by luckysori** [comment] 2022-08-29 00:54
I don't think this is a bug. Since https://github.com/itchysats/itchysats/pull/2680 we are sending offers via two different protocols to _all_ takers. One of those protocols will always fail during the negotiation phase. I documented this behaviour here: e4f910f35070c47672c8e37e224b51e3b532e833.

As noted in that commit message, on the maker side we can suppress these warnings because we can choose to ignore that specific error when opening the substream. On the taker side it is emitted in a place where we handle all possible incoming substreams, so it's unavoidable.

To not send needless offers to takers we need to evolve the `Endpoint` to be able to decide during runtime what protocol to dial to which takers, depending on their supported listen protocols.

---

If you look at the [Grafana logs](https://itchysats.grafana.net/explore?orgId=1&left=%7B%22datasource%22:%22grafanacloud-itchysats-logs%22,%22queries%22:%5B%7B%22refId%22:%22A%22,%22editorMode%22:%22builder%22,%22expr%22:%22%7Bsetup%3D%5C%22testnet%5C%22%7D%20%7C%3D%20%60negotiation%20failed%60%22,%22queryType%22:%22range%22%7D%5D,%22range%22:%7B%22from%22:%221660809217202%22,%22to%22:%221661734356186%22%7D%7D) you can see that the frequency for this particular log message increased just after https://github.com/itchysats/itchysats/pull/2680 merged.

**Comment by luckysori** [comment] 2022-08-29 00:56
I'm removing the `bug` label given what I mentioned in my previous comment. I'll assign myself to this ticket and repurpose it to describe the current behaviour and how I think we should solve it.

**Comment by luckysori** [comment] 2022-08-29 01:23
I don't see this log anywhere in Grafana. Could it be that the oracle was down for some time whilst `BETHUSD` events were being added?

**Comment by luckysori** [comment] 2022-08-29 01:26
The rollovers started working again after a few minutes. Closing because I've confirmed that Olivia was down during that period of time.

**Closed as not planned by luckysori** 2022-08-29 01:26 UTC
Labels: bug

**Comment by bonomat** [comment] 2022-08-29 03:36
The log was collected locally.

> The rollovers started working again after a few minutes. Closing because I've confirmed that Olivia was down during that period of time.

How did you confirm the oracle was down?

**Comment by luckysori** [comment] 2022-08-29 03:59
> The log was collected locally.

Yeah, but what I meant is that no testnet taker failed similarly. Nor did either of the makers fail to get announcements in the last few days.

> How did you confirm the oracle was down?

I inferred that it was from my communication with Lloyd. But I've gone back and asked him explicitly.

**Comment by bonomat** [comment] 2022-08-29 04:32
Thanks. Happy to keep it closed and monitor if it happens again.
