### ISSUE TITLE
Do not hard-code `{Setup,Rollover}Params` fee rate

### ISSUE THREAD

**Issue by luckysori** [itchysats/itchysats#1094] opened 2022-01-14 01:01 UTC
After the event-sourcing refactor, we started to hard-code the `fee_rate` used to calculate fees in `maia` for contract setup and rollover.

The three places where we currently hard-code the `fee_rate` are:

https://github.com/itchysats/itchysats/blob/849226df74d3cf43005d178222a40db49ddab140/daemon/src/model/cfd.rs#L635

https://github.com/itchysats/itchysats/blob/849226df74d3cf43005d178222a40db49ddab140/daemon/src/model/cfd.rs#L668

https://github.com/itchysats/itchysats/blob/849226df74d3cf43005d178222a40db49ddab140/daemon/src/model/cfd.rs#L695

Without this, waiting for transactions could take too long.

Some of the previously closed issues that introduced the functionality originally: #830 #677.

**Comment by klochowicz** [comment] 2022-01-14 01:04
duplicate of #1093 😀

**Comment by luckysori** [comment] 2022-01-14 01:06
> duplicate of #1093 :p

lol I just wanted to link to an issue in my PR: https://github.com/itchysats/itchysats/pull/1095 :(

**Comment by da-kami** [comment] 2022-01-25 00:16
We will need to communicate the fee from maker to taker (the maker being in control of the fees) for contract setup and rollover. 

For the contract setup we already have it in the offer. For rollover we will have to extend the accepted message from maker to taker.

**Closed as completed** 2022-01-25 07:31 UTC
