### ISSUE TITLE
Contract setup commands ("accept", "reject") should return a failed event instead of logging error

### ISSUE THREAD

**Issue by klochowicz** [itchysats/itchysats#1035] opened 2022-01-07 01:10 UTC
After an error during contract setup (due to loss of connection from the taker if I remember correctly), the maker got stuck with an cfd that could be neither accepted nor rejected.
Both commands were indicating that they can't success, logs were informing me about this, but no event was produced; this meant that the cfd was stuck in this state forever.
This example shows that if we *know* what should be the next event (in this case, `ContractSetupFailed`), we should return that event from the command and apply it. 

note: this problem might be applicable to other events as well

**Comment by da-kami** [comment] 2022-01-09 22:58
#1048 might be a duplicate of this ticket. Only noticed later that this might be describing the same issue.

**Comment by thomaseizinger** [comment] 2022-01-11 01:49
I am allowing this to be closed by #1058 because it solves the deadlock that we discovered. Let's see if more instances of this come up after this!

**Closed as completed** 2022-01-11 06:12 UTC
Labels: bug
