### ISSUE TITLE
Regularly erroring/timing out when negotiating protocol

### ISSUE THREAD

**Issue by bonomat** [itchysats/itchysats#2483] opened 2022-07-20 04:06 UTC
I had 10 takers running over the last 20h and they reported the following error `1761` times: 

```
2022-07-19 12:00:01 ERROR Handle Ping:open_substream: xtra_libp2p::endpoint: error=Timeout in protocol negotiation peer=PeerId("12D3KooWEsK2X8Tp24XtyWh7DM65VfwXtNH2cmfs2JsWmkmwKbV1") protocols=["/ipfs/ping/1.0.0"] connection_timeout=20s
```

calculated with: 
```
docker-compose logs  2>&1 | grep -c "ERROR Handle Ping:open_substream: xtra_libp2p::endpoint"
890
```

From what I can tell there was no restart on the maker side.

**Comment by luckysori** [comment] 2022-08-08 05:52
Duplicate of #2602.

**Closed as not planned by luckysori** 2022-08-08 05:52 UTC
