### ISSUE TITLE
Parties get stuck in contract setup after order is accepted

### ISSUE THREAD

**Issue by da-kami** [itchysats/itchysats#1606] opened 2022-03-10 11:01 UTC
Maker and Taker running from branch `two-funding-rates-taker-ui`.
Automation running on my latest branch. Prices hardcoded, funding rate hardcoded to 0.

What I did:

Long -> Confirm
Short -> Confirm

Behavior:

* Taker sends out orders
* Maker accepts
* Taker receives the accept (so it seems it made it into the setup actor)
* Nothing happens, taker UI forever stuck in 

No errors or warnings, but obviously something went wrong.
For contract setup the maker still sends messages using `.send` to the actors. How are we not seeing error(s)?

Taker logs:

```
2022-03-10 10:47:36 DEBUG shared_bin::fairings: HTTP request=GET /api/feed text/event-stream
2022-03-10 10:51:10 DEBUG shared_bin::fairings: HTTP request=POST /api/cfd/order application/json
2022-03-10 10:51:10  INFO daemon::taker_cfd: Taking current order: Order { id: OrderId(Hyphenated(0a9659f9-a2eb-46b6-be29-777ad05dc09c)), trading_pair: BtcUsd, position_maker: Short, price: Price(40410.10), min_quantity: Usd(100), max_quantity: Usd(1000), leverage_taker: Leverage(2), liquidation_price: Price(26940.066666666666666666666667), creation_timestamp: Timestamp(1646909449), settlement_interval: Duration { seconds: 86400, nanoseconds: 0 }, origin: Theirs, oracle_event_id: BitMexPriceEventId { timestamp: OffsetDateTime { utc_datetime: PrimitiveDateTime { date: Date { year: 2022, ordinal: 70 }, time: Time { hour: 11, minute: 0, second: 0, nanosecond: 0 } }, offset: UtcOffset { hours: 0, minutes: 0, seconds: 0 } }, digits: 20 }, tx_fee_rate: TxFeeRate(1), funding_rate: FundingRate(0.0), opening_fee: OpeningFee { fee: Amount(0.00000000 BTC) } }
2022-03-10 10:51:10  INFO daemon::setup_taker: Order got accepted order_id=0a9659f9-a2eb-46b6-be29-777ad05dc09c
2022-03-10 10:51:21 DEBUG shared_bin::fairings: HTTP request=POST /api/cfd/order application/json
2022-03-10 10:51:21  INFO daemon::taker_cfd: Taking current order: Order { id: OrderId(Hyphenated(49b07b21-bc1a-4e83-8760-9570eee1e4b0)), trading_pair: BtcUsd, position_maker: Long, price: Price(39600.00), min_quantity: Usd(100), max_quantity: Usd(1000), leverage_taker: Leverage(2), liquidation_price: Price(26400.00), creation_timestamp: Timestamp(1646909470), settlement_interval: Duration { seconds: 86400, nanoseconds: 0 }, origin: Theirs, oracle_event_id: BitMexPriceEventId { timestamp: OffsetDateTime { utc_datetime: PrimitiveDateTime { date: Date { year: 2022, ordinal: 70 }, time: Time { hour: 11, minute: 0, second: 0, nanosecond: 0 } }, offset: UtcOffset { hours: 0, minutes: 0, seconds: 0 } }, digits: 20 }, tx_fee_rate: TxFeeRate(1), funding_rate: FundingRate(0.0), opening_fee: OpeningFee { fee: Amount(0.00000000 BTC) } }
2022-03-10 10:51:21  INFO daemon::setup_taker: Order got accepted order_id=49b07b21-bc1a-4e83-8760-9570eee1e4b0
```

Maker logs:

```
2022-03-10 10:51:10 DEBUG daemon::maker_cfd: Taker wants to take an order taker_id=ba4a7001bb1debc4e355f971e7e87409281865691ae64cbd9c8cfac1a07da442 quantity=100 order_id=0a9659f9-a2eb-46b6-be29-777ad05dc09c
2022-03-10 10:51:10 DEBUG shared_bin::fairings: HTTP request=POST /api/cfd/0a9659f9-a2eb-46b6-be29-777ad05dc09c/acceptOrder application/json
2022-03-10 10:51:10 DEBUG daemon::maker_cfd: Maker accepts order order_id=0a9659f9-a2eb-46b6-be29-777ad05dc09c
2022-03-10 10:51:10  INFO daemon::setup_maker: Maker accepts an order order_id=0a9659f9-a2eb-46b6-be29-777ad05dc09c
2022-03-10 10:51:21 DEBUG daemon::maker_cfd: Taker wants to take an order taker_id=ba4a7001bb1debc4e355f971e7e87409281865691ae64cbd9c8cfac1a07da442 quantity=100 order_id=49b07b21-bc1a-4e83-8760-9570eee1e4b0
2022-03-10 10:51:21 DEBUG shared_bin::fairings: HTTP request=POST /api/cfd/49b07b21-bc1a-4e83-8760-9570eee1e4b0/acceptOrder application/json
2022-03-10 10:51:21 DEBUG daemon::maker_cfd: Maker accepts order order_id=49b07b21-bc1a-4e83-8760-9570eee1e4b0
2022-03-10 10:51:21  INFO daemon::setup_maker: Maker accepts an order order_id=49b07b21-bc1a-4e83-8760-9570eee1e4b0
```

Taker UI stuck in `Contract Setup`:

![image](https://user-images.githubusercontent.com/5557790/157648615-ed96dd26-b2cc-4336-b950-a12e1a6a39a7.png)

**Comment by luckysori** [comment] 2022-03-11 01:09
After looking at this for a bit, we were not able to reproduce it again. Some notes:

- It does not seem like it would have anything to do with the hard-coded prices or funding rate.

- It is interesting that it looks like we're not getting stuck in an `xtra` handler because we don't hear about a handler processing a message for X seconds.

- The message that should come next for both parties is `Exchanged setup parameters`.

- Await points between the last log and the expected next log (on the taker side):

    1. `Exectutor::execute`. Acquiring a connection to the db and loading the CFD could hang silently. Sending a message to the process manager should not hang silently.
    2. We then spawn the `setup_contract` future which could not block the entire application. None of the `await` points in there before the `Exchanged setup parameters` message is logged don't look like good candidates for silently hanging: two related to `xtra` handlers that should report hanging; and another which would time out after a minute.
    
Maybe someone can figure something out with this information, but given our inability to reproduce it I think we can either close this or not prioritize it.

**Comment by bonomat** [comment] 2022-03-22 00:15
Closing this for now as we cannot reproduce it.

**Closed as completed by bonomat** 2022-03-22 00:15 UTC
Labels: bug
