### ISSUE TITLE
Pressing `Long` for BTCUSD opens a `Short` position

### ISSUE THREAD

**Issue by da-kami** [itchysats/itchysats#2774] opened 2022-08-29 09:02 UTC
![image](https://user-images.githubusercontent.com/5557790/187164988-9d144168-a897-4dbf-a6ee-0d1c55de0632.png)

I just manually opened a position by pressing `Long`, but that resulted in a `Short` position in the UI. I did it again to verify the behavior and same happened. I think something is flipped somewhere (at least for `BTCUSD`).

**Comment by da-kami** [comment] 2022-08-29 09:08
Might be related to https://github.com/itchysats/itchysats/pull/2764

**Comment by da-kami** [comment] 2022-08-29 09:12
Can confirm that `ETHUSD` has the same behavior:

![image](https://user-images.githubusercontent.com/5557790/187167144-b6e74586-003a-44a3-801d-d332c301f600.png)

**Comment by bonomat** [comment] 2022-08-30 04:36
The problem is that somehow long and short offers are swapped. Also on the maker side: 

<img width="1049" alt="image" src="https://user-images.githubusercontent.com/224613/187350204-05f4a196-1277-49b8-a194-5011a6ea1eb9.png">

**Comment by bonomat** [comment] 2022-08-31 05:34
Closing this in favor of #2760

**Closed as completed by bonomat** 2022-08-31 05:34 UTC
Labels: bug
