### ISSUE TITLE
Takers fail to open position because `Offer with id ... not found in current offers`

### ISSUE THREAD

**Issue by da-kami** [itchysats/itchysats#2725] opened 2022-08-20 08:55 UTC
Given [the logs showing `Contract setup completed`]() it looks like this is a temporary problem, i.e. taker(s) have an outdated `offer` but only temporarily and are able to open a position eventually.

Recommendation for further analysis:

- Relate+log the `peer_id` to the place where we log the error, at the moment the `peer_id` is not part of it so it is impossible to track which takers have this problem.
- Go through the state management of the `offer`. How can we better ensure that the taker does not have an outdated offer?
   - It appears this problem happens when the maker is ahead of the taker in terms of the `offer`. This is related to placing the order using the offer-id. However, given that in the past this worked more stable, there is likely a bug in the state management of the offer on the taker side. How should the offer state change if we e.g. disconnect from the maker?

**Comment by bonomat** [comment] 2022-08-28 23:18
This happens regularly now on mainnet

**Comment by luckysori** [comment] 2022-09-02 08:29
It looks like this is caused by the well known https://github.com/itchysats/itchysats/issues/2602.

This is the pattern that we see in the logs every time we get the `Offer with id ... not found in current offers` error:

![image](https://user-images.githubusercontent.com/9418575/188098253-1c30455d-849b-4dcf-a617-2e7041f7a470.png)

Given the cause I'm gonna close this issue, because the problem is tracked elsewhere.

**Closed as completed by luckysori** 2022-09-02 08:29 UTC
Labels: bug
